### PR TITLE
remove default profile fields; fix minor typo

### LINKED ISSUE #50: Default profile fields
According to the [messenger docs](https://developers.facebook.com/docs/messenger-platform/identity/user-profile), the default fields have changed and to access the other fields, one has to ask for access.

From my usage of other bots building libraries/software and also bare development without one, this will throw permission error and we'd have to change the default fields.

I am working on a simple PR to change these --the default fields.

### PR DESCRIPTION
**Pull request by OAyomide**
This is the PR to fix #50

### CODE REVIEW

File: examples/basic/main.go [hunk 1]
```diff
@@ -8,16 +8,18 @@ import (
 	"os"
 	"time"
 
+	msgs "github.com/messenger"
```
Comment (paked) [inline examples/basic/main.go]: Travis is breaking because this repository doesn't exist, should probably be changed to: github.com/paked/messenger

I also don't think using an alias on this package is a good idea. It's fine for your own code, but should be avoided because this is an "official" example.

Comment (OAyomide) [reply examples/basic/main.go]: Yeah... I am really sorry about that. I developed and it worked for me locally so I didn't bother to check over. I am so sorry! :upside_down_face: I didn't realize it'd reference my second commit as I wasn't really ready to submit the PR.

So I should make a fix for those then.

File: examples/basic/bot.config.yml [hunk 2]
```diff
@@ -0,0 +1,5 @@
+verify_token: <verify_token_here>
```
Comment (paked) [inline examples/basic/bot.config.yml]: As we concluded in #52 that we want to separate configuration from this package, would you mind removing those related-changes from this PR?

File: examples/basic/main.go [hunk 3]
```diff
@@ -7,17 +7,17 @@ import (
 	"net/http"
 	"os"
 	"time"
-
```
Comment (paked) [inline examples/basic/main.go]: It's pedantic, but I prefer to keep my stdlib and non-stdlib dependencies separated -- so please revert to having the newline there.

File: parser.go [hunk 4]
```diff
@@ -0,0 +1,45 @@
+package messenger
```
Comment (paked) [inline parser.go]: As discussed above, we won't need this file.

File: examples/basic/main.go [hunk 5]
```diff
@@ -7,17 +7,17 @@ import (
...
 	"github.com/paked/messenger"
 )
 
+var vt, acct, appsc = messenger.GetTokens()
```
Comment (paked) [inline examples/basic/main.go]: Should revert this back too

**Review by paked — CHANGES_REQUESTED** [review]
Thanks for the PR!

I really appreciate you wanting to contribute to this package, but because of the discussion in #50 I need to ask you to make a few changes --  apart from that everything looks great!

Just a heads up next time you make a contribution, it'd be really helpful for me if you split your unrelated changes into different pull requests. It makes the entire process much quicker :)

**Comment by OAyomide** [comment]
Hey! Thanks!

I do understand your point. I'll revert those and make the PR again.  :upside_down_face:

**Comment by pranas** [comment]
I have concerns about this change, see [here](https://github.com/paked/messenger/issues/50#issuecomment-450959151).

**Comment by OAyomide** [comment]
@pranas @paked can you review please? I made the changes as discussed in #50 

If all is well, perhaps I could go ahead and fix the example(s) :upside_down_face:

**Comment by OAyomide** [comment]
@paked sorry for the never-ending commits! :see_no_evil: I didn't realize the example would make the build fail.

File: examples/basic/main.go [hunk 6]
```diff
@@ -11,6 +11,10 @@ import (
 	"github.com/paked/messenger"
 )
 
+//profileField is a slice of strings of the user profile field the developer wants access
+var (
+	profileField = []string{"name", "first_name", "last_name", "profile_pic"}
```
Comment (paked) [inline examples/basic/main.go]: I would inline this slice, so it looks like:

```
p, err := client.ProfileByID(m.Sender.ID, []string{"name", "first_name", "last_name", "profile_pic"})
```

It's only used in one place, so we don't need to add an extra level of indirection.

File: examples/linked-account/main.go [hunk 7]
```diff
@@ -14,6 +14,11 @@ import (
 	"github.com/paked/messenger"
 )
 
+//profileField is a slice of strings of the user profile field the developer wants access
+var (
+	profileField = []string{"name", "first_name", "last_name", "profile_pic"}
```
Comment (paked) [inline examples/linked-account/main.go]: Same here

File: messenger.go [hunk 8]
```diff
@@ -154,17 +150,16 @@ func (m *Messenger) Handler() http.Handler {
...
-// 
-// These default fields are:
-// - First name
-// - Last name
-// - Profile picture
-// - Locale
-// - Timezone
-// - Gender
-func (m *Messenger) ProfileByID(id int64, profileFields ...string) (Profile, error) {
+// ProfileByID retrieves the Facebook user profile associated with that ID.
```
Comment (paked) [inline messenger.go:152]: I like this comment!

File: messenger.go [hunk 9]
```diff
@@ -154,17 +150,16 @@ func (m *Messenger) Handler() http.Handler {
...
+// According to the messenger docs: https://developers.facebook.com/docs/messenger-platform/identity/user-profile,
+// Developers must ask for access except for some fields that are accessible without permissions.
+//
+// These fields are
```
Comment (paked) [inline messenger.go]: Can we change this to "At the time of writing (2019-01-04), these fields are:"

File: messenger.go [hunk 10]
```diff
@@ -174,7 +169,7 @@ func (m *Messenger) ProfileByID(id int64, profileFields ...string) (Profile, err
 	}
 
 	if len(profileFields) == 0 {
```
Comment (paked) [inline messenger.go]: I don't think we need to throw an error here, since there are cases where you might want to retrieve a profile with no information: potentially you just want to see if the profile exists in the first place (in which case as long as there isn't an error you should be OK).

**Review by paked — CHANGES_REQUESTED** [review]

**Comment by paked** [comment]
Okay, wow. I think that was the last review. After those changes we should be good to merge.

File: examples/basic/main.go (hunk 6 above)
Comment (pranas) [reply examples/basic/main.go]: +1

**Comment by OAyomide** [comment]
Got it @paked

I'll jump on it and make the changes promptly.

**Comment by paked** [comment]
Thanks for sticking with me through the twisty turn-y path we used to get to this point!

If you're looking for another issue to work on, #55 would be great.
